# Generated by Django 4.1 on 2024-03-20 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='create_time',
        ),
    ]
