# Generated by Django 4.2.7 on 2024-03-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaster',
            name='contact',
            field=models.CharField(default='', max_length=255),
        ),
    ]
