# Generated by Django 4.2.7 on 2024-03-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_disaster_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disaster',
            name='is_delete',
        ),
        migrations.AddField(
            model_name='disaster',
            name='is_onging',
            field=models.BooleanField(default=True),
        ),
    ]
