# Generated by Django 4.2.7 on 2024-03-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_disaster_is_verified_disaster_radius_disaster_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='radius',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='log',
            name='type',
            field=models.CharField(default='', max_length=40),
        ),
    ]
