# Generated by Django 4.2.7 on 2024-03-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_alter_log_responsible_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaster',
            name='type',
            field=models.CharField(default='Car Accident', max_length=40),
        ),
    ]
