# Generated by Django 4.2.7 on 2024-03-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_alter_log_responsible_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaster',
            name='image_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='log',
            name='image_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='type',
            field=models.CharField(default='Car Accident', max_length=40),
        ),
    ]
