# Generated by Django 4.2.7 on 2024-03-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_disaster_image_url_log_image_url_alter_disaster_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disaster',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='disaster',
            name='verified_status',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
